services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
